Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using contosoUniversity2020.Data;
using contosoUniversity2020.Models;
using Microsoft.AspNetCore.Authorization;

namespace contosoUniversity2020.Controllers
{
        //mwilliams: Part 12: Authorization (securing admin controllers)
        [Authorize(Roles = "Admin")]

        //mwilliams: Part 4: Scaffold Models and Customize Views

    public class CourseController : Controller
    {
        private readonly SchoolContext _context;

        public CourseController(SchoolContext context)
        {
            _context = context;
        }

        // GET: Course
        public async Task<IActionResult> Index()
        {
            var schoolContext = _context.Courses.Include(c => c.Department);
            return View(await schoolContext.ToListAsync());
        }
        [AllowAnonymous]
        // GET: Course/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(c => c.Department)
                .FirstOrDefaultAsync(m => m.CourseID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Course/Create
        public IActionResult Create()
        {
            ViewData["DepartmentID"] = new SelectList(_context.Departments, "DepartmentID", "Name");
            return View();
        }

        // POST: Course/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CourseID,Title,Credits,DepartmentID")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentID"] = new SelectList(_context.Departments, "DepartmentID", "Name", course.DepartmentID);
            return View(course);
        }

        // GET: Course/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            ViewData["DepartmentID"] = new SelectList(_context.Departments, "DepartmentID", "Name", course.DepartmentID);
            return View(course);
        }

        // POST: Course/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CourseID,Title,Credits,DepartmentID")] Course course)
        {
            if (id != course.CourseID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.CourseID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentID"] = new SelectList(_context.Departments, "DepartmentID", "Name", course.DepartmentID);
            return View(course);
        }

        // GET: Course/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(c => c.Department)
                .FirstOrDefaultAsync(m => m.CourseID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Course/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Courses.FindAsync(id);
            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Courses.Any(e => e.CourseID == id);
        }

        //mwilliams: Custom Listing method for guest users
        // (non registered not logger in users)
        [AllowAnonymous]
        public async Task<IActionResult> Listing(int? selectedDepartment)
        {
            //the selectedDepartment above refers to a dropdownlist (select) int the corresponding
            //View
            IQueryable<Course> courses = GetCourses(selectedDepartment);
            return View(await courses.ToListAsync());
        }

        private IQueryable<Course> GetCourses(int? selectedDepartment)
        {
            //Get all departments sorted by name
            var departments = _context.Departments.OrderBy(d => d.Name).ToList();

            ViewData["selectedDepartment"] =
                new SelectList(departments, "DepartmentID", "Name", selectedDepartment);
            //<select name="selectedDepartment">
            //  <option value="1" selected>Accounting</option>
            //</select>

            //retrieve the incoming id parameter value
            int departmentId = selectedDepartment.GetValueOrDefault();

            //get courses only for a single selected department 
            IQueryable<Course> courses = _context.Courses
                .Where(c => !selectedDepartment.HasValue ||
                            c.DepartmentID == departmentId)
                        .OrderBy(d => d.CourseID)
                        .Include(d => d.Department);

            return courses;
        }
    }
}

Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using contosoUniversity2020.Data;
using contosoUniversity2020.Models;
using contosoUniversity2020.Models.SchoolViewModels;
using Microsoft.AspNetCore.Authorization;

namespace contosoUniversity2020.Controllers
{
    //mwilliams: Part 12: Authorization (securing admin controllers)
    [Authorize(Roles = "Admin")]

    //mwilliams: Part 4: Scaffold Models and Customize Views

    public class StudentController : Controller
    {
        private readonly SchoolContext _context;

        public StudentController(SchoolContext context)
        {
            _context = context;
        }

        // GET: Student
        public async Task<IActionResult> Index()
        {
            return View(await _context.Students.ToListAsync());
        }

        // GET: Student/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .FirstOrDefaultAsync(m => m.ID == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Student/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Student/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EnrollmentDate,ID,FirstName,LastName,Email,Address,City,Province,PostalCode")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Student/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: Student/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EnrollmentDate,ID,FirstName,LastName,Email,Address,City,Province,PostalCode")] Student student)
        {
            if (id != student.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Student/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .FirstOrDefaultAsync(m => m.ID == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Student/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var student = await _context.Students.FindAsync(id);
            _context.Students.Remove(student);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentExists(int id)
        {
            return _context.Students.Any(e => e.ID == id);
        }
        //mwilliams: Part 7: Creating View Models
        //2. Create the Stats ActionResult Method
        public async Task<IActionResult> Stats()
        {
            //Populate the EnrollmentDateGroup ViewModel with Student Statistics
            //Counting the number of students by their enrollment date
            //using LINQ (Language Integrated Query)
            /* This is the SQL Version
               SELECT COUNT(*) as StudentCount, EnrollmentDate from person
               WHERE discriminator = 'student'
               GROUP BY EnrollmentDate
             */
            IQueryable<EnrollmentDataGroup> data =
                from Student in _context.Students//FROM Students
                group Student by Student.EnrollmentDate into dateGroup
                select new EnrollmentDataGroup //SELECT EnrollmentDate, COUNT(*) as StudentCounter
                {
                    EnrollmentDate = dateGroup.Key,
                    StudentCount = dateGroup.Count()
                };
            //return the view with populate EnrollmentDateGroup object
            return View(await data.ToListAsync());
            }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Contoso University</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="//fonts.googleapis.com/css?family=Open Sans&subset=latin" rel="stylesheet" type="text/css">
    @RenderSection("CSS", required: false)
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="d-flex flex-column h-100 min-vh-100">
    <a href="scrolltopbutton"></a>
    <header>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">*@
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark box-shadow mb-3 fixed-top">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Contoso University</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i> Home</a>
                        </li>
                        <partial name="_MenuPartial"/>


                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About"><i class="fas fa-info-circle"></i> About Us</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @RenderSection("Carousel",required:false)
    <main role="main" class="flex-shrink-0">
        <div class="container mt-3">
            @RenderBody()
        </div>
    </main>


    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2020 - ContosoUniversity2020 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>*@
    <footer class="mt-auto pt-3">
        <div id="main-footer" class="py-3">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3">
                        <div>
                            <h5>Our Contact</h5>
                            <address>
                                <strong>Contoso University</strong><br>
                                100 Cameron Street<br>
                                Moncton, NB E1C 5Y6
                            </address>
                            <p>
                                <i class="icon-phone"></i> (506) 858-9696 <br>
                                <i class="icon-envelope-alt"></i> inquire@contoso.com
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div>
                            <h5>Quick Links</h5>
                            <ul class="link-list">
                                <li><a href="#">Latest Events</a></li>
                                <li><a href="#">Our Programs</a></li>
                                <li><a href="#">Career</a></li>
                                <li><a href="#">Contact us</a></li>
                                <li><a href="#">Terms and conditions</a></li>
                                <li><a asp-controller="Home" asp-action="Privacy">Privacy</a></li>

                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div>
                            <h5>Latest posts</h5>
                            <ul class="link-list">
                                <li><a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></li>
                                <li><a href="#">Pellentesque et pulvinar enim. Quisque at tempor ligula</a></li>
                                <li><a href="#">Natus error sit voluptatem accusantium doloremque</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div>
                            <h5>Recent News</h5>
                            <ul class="link-list">
                                @await  Component.InvokeAsync("NewsWidget")
                                @*or
                                            @await  Component.InvokeAsync("NewsWidget", new ( threshold = 4))
                                *@
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="sub-footer" class="py-3">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7">
                        <span>&copy; @DateTime.Now.Year - Contoso University</span>
                    </div>
                    <div class="col-5">
                        <ul class="float-right social-network">
                            <li><a href="#" title="Find us onFacebook"><i class="fab fa-facebook-f"></i></a></li>
                            <li><a href="#" title="Follow us on Twitter"><i class="fab fa-twitter"></i></a></li>
                            <li><a href="#" title="Connect with us on Linkedin"><i class="fab fa-linkedin-in"></i></a></li>
                            <li><a href="#" title="Follow us on Instagram"><i class="fab fa-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://kit.fontawesome.com/423b6167dd.js" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_MenuPartial.cshtml
@*mwilliams: Authentication and Authorization
    Authenticated: I have successfully logged in (user|pwd)
    Authorized:    What can I see (am I and admin, student or instructor): Roles
*@
@if (User.Identity.IsAuthenticated)
{
    //User is authenticate (either an Admin, Student, or Instructor)


    if (User.IsInRole("Admin"))
    {
        //CONDITION 1: ADMIN
        //all original code from below belongs here
        @*Students DropDown menu*@
        <li class="nav-item dropdown">
            <a title="Students" class="nav-link dropdown-toggle" href="#"
               id="studentDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="far fa-address-book"></i> Students
            </a>
            <div class="dropdown-menu" aria-labelledby="studentDropdown">
                <a class="dropdown-item" asp-controller="Student" asp-action="Index"><i class="fas fa-users"></i>Students</a>
                <a class="dropdown-item" asp-controller="Course" asp-action="Index"><i class="fas fa-address-book-book"></i>Courses</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" asp-controller="Enrollment" asp-action="Index">Enrollment</a>
                @*<a class="dropdown-item" asp-controller="Course" asp-action="Index">Stats Report</a>*@
            </div>
        </li>

        @*Faculty DropDown menu*@
        <li class="nav-item dropdown">
            <a title="Faculty" class="nav-link dropdown-toggle text-light" href="#"
               id="facultyDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="far fa-building"></i> Faculty
            </a>
            <div class="dropdown-menu" aria-labelledby="facultyDropdown">
                <a class="dropdown-item" asp-controller="Instructor" asp-action="Index"><i class="fas fa-chalkboard-teacher"></i> Instructors</a>
                <a class="dropdown-item" asp-controller="Department" asp-action="Index"><i class="fas fa-sitemap"></i> Departments</a>

            </div>
        </li>}
    else if (User.IsInRole("Student"))
    {

        //CONDITION 2: STUDENT
        <li class="nav-item">
            <a class="nav-link text-light" asp-area="" asp-controller="StudentEnrollment"
               asp-action="Index"><i class="fas fa-list-ol"></i> Your Courses</a>
        </li>
    }
    else if (User.IsInRole("Instructor"))
    {
        //CONDITION 3: INSTRUCTOR
        <li class="nav-item">
            <a class="nav-link text-light" asp-area="" asp-controller="InstructorCourse"
               asp-action="Index"><i class="fas fa-list-ol"></i> Your Courses</a>
        </li>
    }

}
else
{
    //User is not authenticated (guest): show the guest and menu links
    <li class="nav-item">
        <a class="nav-link text-light" asp-area="" asp-controller="Course"
           asp-action="Listing"><i class="fas fa-list-ol"></i> Our Courses</a>
    </li>
}